<table align=center>
<tr>
<th colspan=2 bgcolor=lightblue>  <font color=red> Stickleback </font> </th>
</tr>
<tr>
<td> <img src="http://www.indiana.edu/~jkkteach/consumer_learning/exp03/Boatdb2.gif" height=86 width=225>
</td>

<td>
The Society of Whitewater Rafters emphasizes:
<ul>
<font color=red> <li> 
<font color=black> <b><i> [CueC] </b> </i></li> 
<font color=red> <li> 
<font color=black> <b> <i> [CueD] </b></i> </li>
</ul>
Overall Quality Rating: <strong> [OutE] </strong> 
</td>
</tr>
<tr>
<th colspan=2 bgcolor=lightblue> &nbsp; </th>
</tr>
</table>

<table align="center" width="90%"> <tr> <td>For extended journeys, a
real workhorse but maneuverable too. It has 14 air compartments, 7
fitted D-rings, it weighs 75 kg, and it can accommodate a maximum crew
of 5. The Society of Whitewater Rafters emphasizes that this raft has
[CueC] and it has [CueD]. They rate the overall quality of this raft
as [OutE].  </td> </tr> </table>






