
```{r child = '_poem_r_code.Rmd'}
```
<br>

## Cueva de las Manos
<br>

<!-- 212 words -->

[Withheld until publication.]

<!-- Shadowy menageries of rabbits,\ -->
<!-- birds and bees, of urges and bad habits,\ -->
<!-- slither across the chained spelunker's wall,\ -->
<!-- lit from behind by FX digital:\ -->
<!-- a sorcerer's hands, contorted fingers,\ -->
<!-- cast illusions while cave eyes malinger.\ -->
<!-- A mouse on the wall tells time with two splayed\ -->
<!-- hands, white gloved, the big one spinning fast, made\ -->
<!-- to emphasize the passing of minutes\ -->
<!-- while the small hand smuggles to begin its\ -->
<!-- inobtrusive countdown of the hours\ -->
<!-- prankster Mickey laughingly devours.\ -->
<!-- To fend off wasted time, envies, regrets,\ -->
<!-- another wall clock's arms have amulets:\ -->
<!-- two hamsa hands that protect or provide,\ -->
<!-- one hamsa blessed, one never evil eyed.\ -->
<!-- Concentric gestures sweep the dial's face\ -->
<!-- but never will those hamsa hands embrace.\ -->
<!-- Outside the cave, two lovers orbit hand\ -->
<!-- in hand pointing to nothing but a sand\ -->
<!-- grain's weightless free fall in their hourglass,\ -->
<!-- to dandelions floating over grass,\ -->
<!-- contriving no manipulation of\ -->
<!-- shadows, protecting one provision: love.\ -->
<!-- To mark their union, they pack mineral\ -->
<!-- pigments to the sacred cave, where they will\ -->
<!-- splay their hand, one lover's-hand thickness off\ -->
<!-- the wall, while the lover blows powder soft,\ -->
<!-- paints a canvas with reverse silhouette\ -->
<!-- that twenty thousand years will not forget,\ -->
<!-- so now we may hold our own hands with care\ -->
<!-- one lover's-hand thickness away from theirs.\ -->

`r end_poem_mark`

<small>

`r qrc_png( url = "https://www.theargylelitmag.com/poetry-1" , journal_name = "*The Argyle Literary Magazine*" , publication_info = "Issue 5, 15 September 2025.")`

*Notes:* 

`r link_new_tab( url = "https://whc.unesco.org/en/list/936/" , display_text = "La Cueva de las Manos" )`, in Argentina, contains many paintings of hands, approximately 10,000 years old. Based on attempts to reproduce the appearance of ancient hand paintings that mark the area around a hand (in Europe), `r link_new_tab( url = "https://doi.org/10.1016/j.jas.2022.105574" , display_text = "one recent theory" )`  is that people blew mineral pigments — such as calcite, limonite, iron and manganese oxides — through a hollowed bone tube over an outstretched hand. But to achieve the effect found in the cave paintings, the hand was probably held slightly away from the wall, not against the wall. This feeling of not-quite contact intrigued me, and when I combined it with lovers holding hands, it became "one lover's-hand thickness" away from the wall. I also just like the idea that the hand paintings commemorate lovers, although there is no suggestion of this in the research literature. The poem considers many other versions of hands on cave walls, including shadow hands on Plato's cave, and clock hands on walls. Regarding form: Every line is *decasyllabic*, with rhyming pairs of lines.

`r next_link("poem_cueva_de_las_manos.html")`

</small>
