
```{r child = '_poem_r_code.Rmd'}
```
<br>

## A Way of Waving &vert;&vert; Wavering Away (contrapuntal)

<br>

<html>

<head>
<style>
table, th, td { border: none /* none or 1px solid black; for checking layout */
                border-collapse: collapse;
                padding: 5px 0px; /* top+bottom left+right */
                vertical-align: middle; }
table td:nth-child(1), table th:nth-child(1) { text-align: right; }
table td:nth-child(2), table th:nth-child(2) { text-align: left; }
.spacer { display: inline-block;
          width: 2.5em; /* set width as desired */ }
.center-table { margin-left: auto;
                margin-right: auto; }
</style>
</head>

<body>

<table class="center-table" width="500em" /* set width as desired */ >

<!-- Instruction row -->
<tr>
<td colspan="3" style="text-align: center;">[Read first down each column, then again row by row across columns.]<br><br></td>
</tr>

<!-- Title row -->
<tr>
<td style="vertical-align: bottom;">
  <span style="font-size: 1.2em;"><b>A Way of Waving</b></span>
</td>
<td style="vertical-align: bottom;"><span class="spacer"></span></td>
<td>
  <i>Translated from the English</i>
  <br> <span style="font-size: 1.2em;"><b>Wavering Away</b></span>
</td>
</tr>

<!-- text rows begin here -->
<tr>
<td>A snake slithers</td>
<td><span class="spacer"></span></td>
<td>Like ribbons fluttering</td>
</tr>

<tr>
<td>across blacktop</td>
<td><span class="spacer"></span></td>
<td>at the ends of handlebars</td>
</tr>

<tr>
<td>then ungrips its skin</td>
<td><span class="spacer"></span></td>
<td>molted when fledged</td>
</tr>

<tr>
<td>at the shrugged shoulder</td>
<td><span class="spacer"></span></td>
<td>to the shed.</td>
</tr>

<tr>
<td>Night crawler escapes</td>
<td><span class="spacer"></span></td>
<td>Like cassette tapes,</td>
</tr>

<tr>
<td>from flooded turf</td>
<td><span class="spacer"></span></td>
<td>Play pressed,</td>
</tr>

<tr>
<td>to be impaled and</td>
<td><span class="spacer"></span></td>
<td>rewound and</td>
</tr>

<tr>
<td>plunged into deep water</td>
<td><span class="spacer"></span></td>
<td>unspooled by appetite.</td>
</tr>

<tr>
<td>Vines creep up trunk and branch,</td>
<td><span class="spacer"></span></td>
<td>Like telltales on shrouds</td>
</tr>

<tr>
<td>grope into air</td>
<td><span class="spacer"></span></td>
<td>flail from windward</td>
</tr>

<tr>
<td>blindly indicating</td>
<td><span class="spacer"></span></td>
<td>to reveal the direction</td>
</tr>

<tr>
<td>into empty space</td>
<td><span class="spacer"></span></td>
<td>where you cannot directly sail.</td>
</tr>

<tr>
<td>Seaweeds sway</td>
<td><span class="spacer"></span></td>
<td>Like how ocular floaters</td>
</tr>

<tr>
<td>in tidal pools</td>
<td><span class="spacer"></span></td>
<td>of vitreous humor,</td>
</tr>

<tr>
<td>sniggering against a snorkel mask</td>
<td><span class="spacer"></span></td>
<td>occluding sea and air,</td>
</tr>

<tr>
<td>while breaths<br>squeeze through a tube,</td>
<td><span class="spacer"></span></td>
<td>inspire through averted vision.</td>
</tr>

<tr>
<td>V formation of migrating geese</td>
<td><span class="spacer"></span></td>
<td>Like my migraine aura,</td>
</tr>

<tr>
<td>with pulsating wings</td>
<td><span class="spacer"></span></td>
<td>a corona borealis flickering</td>
</tr>

<tr>
<td>slides overhead</td>
<td><span class="spacer"></span></td>
<td>from fovea to periphery</td>
</tr>

<tr>
<td>toward the horizon,</td>
<td><span class="spacer"></span></td>
<td>is a benediction from God.</td>
</tr>

<tr>
<td>A snail ventures out</td>
<td><span class="spacer"></span></td>
<td>Like how my GPS wristwatch</td>
</tr>

<tr>
<td>during full-moon night</td>
<td><span class="spacer"></span></td>
<td>under satellite sky</td>
</tr>

<tr>
<td>leaves a trail of ooze</td>
<td><span class="spacer"></span></td>
<td>records my position<br>every other second,</td>
</tr>

<tr>
<td>shimmering in starlight<br>from unnamed constellations
</td>
<td><span class="spacer"></span></td>
<td>life’s legacy<br>of disconnected dots.</td>
</tr>

</table>

</body>
</html>

`r end_poem_mark`

<small>

`r qrc_png(qrc_url = "https://johnkruschke.com/poem_waving.html", journal_url = "https://coldmountainreview.appstate.edu/pub/8vkkuwew/release/1?readingCollection=b08857a0" , journal_name = "*Cold Mountain Review*" , publication_info = "Spring &amp; Summer 2026, May 08.")`


*Notes:* 
Nature waving on the left, human nature wavering away on the right, reflecting each other when read across columns. 

Regarding the format: When reading a poetry journal that presented English translations beside originals in languages I don’t know, I realized that the translator could write anything, and I’d have no way of knowing whether it matched the source. 
I was also piqued by the heading that appeared above them: “Translated from the Chinese” (or whatever the language). So I imagined a genre of poems called *“Translated from the English”* in which the translation is a free-association based on the original, such that each enriches the other. I added one essential rule: the pieces must be *contrapuntal*, reading coherently and generating emergent meaning when scanned row by row across columns; otherwise they’d just be two parts of a single poem.

<p>
<audio controls src="poem_waving.mp3" type="audio/mp3"></audio>

<p>
`r next_link("poem_waving.html")`

</small>
