
```{r child = '_poem_r_code.Rmd'}
```
<br>

## Hamster in Your Head

<br>[Withheld until publication.]

<br>
<!-- Hamster in Your Head -->

<!-- If you hold this poem\ -->
<!-- in the rain\ -->
<!-- its fur will get soaking wet.\ -->
<!-- If you hold this poem\ -->
<!-- in the sun\ -->
<!-- it will squint its eyes.\ -->
<!-- If you hold this poem\ -->
<!-- while you laugh\ -->
<!-- it will wiggle its whiskers with delight.\ -->
<!-- If you hold this poem\ -->
<!-- with a friend\ -->
<!-- it may warm both your hearts.\ -->
<!-- If you read this poem\ -->
<!-- with an open mind\ -->
<!-- it may scurry home\ -->
<!-- inside your head,\ -->
<!-- with all its soaking and squinting,\ -->
<!-- wiggling and warming,\ -->
<!-- nestled snug\ -->
<!-- in the sawdust\ -->
<!-- of your childhood memories\ -->
<!-- and the shredded paper\ -->
<!-- of your past loves.\ -->

`r end_poem_mark`

<small>

`r qrc_png(qrc_url = "https://johnkruschke.com/poem_hamster.html", journal_url = "https://www.bearpawartsjournal.com/issues" , journal_name = "*Bear Paw Arts Journal*" , publication_info = "Accepted for Issue 3, scheduled for the end of November, 2025. But, as of the end of March, 2026, Issue 3 has not been published. Repeated emails to the editor at different email addresses have had no responses. I have dutifully withheld posting the poem while it is pending publication...")`


*Notes:* 
This poem was intended as a simple invitation to poetry for the poem-curious. It is supposed to illustrate, in a compact, warm and friendly way, a few of the things a poem can do.
*Personification:* The poem is a person (pet hamsters do have personalities).
*Metaphor:* The poem is a hamster, with fur that can get wet, and whiskers that wiggle, etc.
*More metaphor:* "the sawdust of childhood memories", "the shredded paper of past loves."
*Concrete bodily imagery:* Hold the furry poem, scurry into your head, etc.
Attention to *the sounds of words,* for example the alliteration in "soaking and squinting," "wiggling and warming."
And, the poem concludes with some *classic poetic themes*, of loss and nostalgia. 


<!-- <p> -->
<!-- <audio controls src="poem_hamster.m4a" type="audio/mp4"></audio> -->

<p>
`r next_link("poem_hamster.html")`

</small>
