---
title: "P457/P657 Moral Machines"
subtitle: "Spring Semester, 2022: Tu/Th 3:00PM-4:15PM, Room PY 115"
author: 
- name: "Professor: <a href='https://jkkweb.sitehost.iu.edu/' target='_blank'>John K. Kruschke</a>"
  email: kruschke@indiana.edu
# date: "Version of `r format(Sys.time(), '%H:%M, %d %B, %Y')`"
output:
  html_document:
    number_sections: no
    theme: default
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: 4
editor_options:
  chunk_output_type: console
csl: "C:/Users/John/Desktop/kruschkeLOCAL/Research/apa.csl"
# csl: "nature.csl"
link-citations: yes
bibliography: "C:/Users/John/Desktop/kruschkeLOCAL/Research/references.bib"
# authornote: ""
# abstract: "This is the syllabus for P457/P657 Moral Machines, Spring Semester 2022."
---

```{r echo=FALSE}
bibFile = "C:/Users/John/Desktop/kruschkeLOCAL/Research/references.bib"
citeTitle = function( key , bibfile=bibFile ){
  bibLines = readLines( bibfile ) # every line of bib file
  keyline = grep( key , bibLines , value=FALSE ) # find line with key in it
  if ( length(keyline)>0 ) { # if key is found, search for title in next lines
    tryline = keyline+1
    title = "" 
    while ( title=="" ) {
      searchline = trimws( bibLines[tryline] , "left" ) # trim whitespace from left
      titletry = grep( "^title" , searchline , ignore.case=TRUE , value=TRUE )
      if ( length(titletry) > 0 ) { 
        title = titletry
        # Strip initial characters through to initial "{":
        for ( i in 1:nchar(title) ) {
          if ( substr(title,i,i)=="{" ) {
            title = substr(title,i+1,nchar(title))
            break
          }
        }
        # Strip final "}":
        for ( i in nchar(title):1 ) {
          if ( substr(title,i,i)=="}" ) {
            title = substr(title,1,i-1)
            break
          }
        }
        # Split into words, split by spaces:
        titleWords = strsplit( title, " " )[[1]]
        # Go through words, leaving as-is if there are braces, converting to lowercase if not:
        title = ""
        wordCount = 0
        for ( word in titleWords ) {
          wordCount = wordCount+1
          if ( nchar(word)>0 ) {
            wordA = strsplit(word,"\\{")[[1]]
            if ( length(wordA) > 1 ) { # if there is a "{"
              pre = wordA[1]
              wordB = strsplit(wordA[2],"\\}")[[1]]
              word = paste0(pre,paste0(wordB,collapse=""))
              title = paste0( title , " " , word )
            } else {
              if ( wordCount==1 ) { # if it's the first word, capitalize first letter
                title = paste0( title , " " , 
                                paste0( toupper(substr(word,1,1)) , 
                                        tolower(substr(word,2,nchar(word))) ) )
              } else { # otherwise convert to all lowercase
                title = paste0( title , " " , tolower(word) )
              }
            }
          }
        }
        title = trimws( title , "left" ) # trim whitespace from left
      }
      tryline = tryline+1
    }
    return( paste0("@",key,": ",title) )
  } else {
    return( "(citation key not found)" )
  }
}
```

# Course description

This course is about 

  * the ethical implications of computer programs and robots, and 
  * how to implement ethics or morality in computer programs and robots.

Sophisticated computer programs and robots already have significant ethical impacts on our lives. Consider: automated computer systems that decide which social-media posts are shown to us, or that decide which loan applications are denied, or that decide which job applications are forwarded, or that recommend which incarcerated people are granted parole. Consider self-driving cars that must decide whether to favor the car's occupants or outside pedestrians. Consider autonomous robotic health-care assistants that cajole patients to do things they might not want to do. Consider autonomous military drones that decide whom to kill. How do we check that those systems are being fair and unbiased, and treating people ethically or at least legally? Crucially, how can we possibly program ethics or human morality into computer programs and robots?

This course emphasizes the importance of applying human moral psychology to these issues. Every topic relies on human psychology: What is the psychology of fairness? What is the psychology of explaining or justifying an action? What is the psychology of responsibility and blame? What is the psychology of attributing moral standing or rights? Do those judgments vary across cultures? Importantly, what are the various psychological and evolutionary functions of *human* morality, and should those same functions be mimicked or acknowledged in *artificial* moral agents?

This course is structured as readings with discussion. Students are expected to do extensive reading every week, and to be prepared to discuss the readings in class.


# Required readings

Please purchase this book:

  * `r citeTitle("Christian2020Alignment")`

All required articles will be posted in Canvas. 


# Schedule of topics and readings

The schedule below is the plan as of `r format(Sys.time(), "%b %d, %Y")`. The exact dates or readings may change as the semester progresses. Any changes will be announced in class and on Canvas.


| Week | Day  | Theme | What                              |
| :-:  | :-:  | :---- | :-------------------------------- |
| 1 | Tues | Overview | Welcome and course overview. <br>(In lecture but not assigned reading: `r citeTitle("ScheutzMalle2018MoralRobots")`; and, `r citeTitle("Liao2020IntroAIethics")`. FYI: [Video](https://youtu.be/LuqLEx7gAOE) featuring Scheutz and Malle.)  |
| 1 | Thur |       | **Quiz.** `r citeTitle("Christian2020Alignment")`. **Prologue & Intro & Ch 1.** <br>FYI: Brian Christian summarizes the book in [this video](https://youtu.be/_LYQRE59Uiw), and has a partial summary with extended discussion in [this video](https://youtu.be/YjssfP-SeH4). |
| 2 | Tues |       | **Quiz.** `r citeTitle("Christian2020Alignment")`. **Ch 2.** <br>(FYI, tangential: [Using social media for policing](https://www.theguardian.com/us-news/2021/nov/17/police-surveillance-technology-voyager).) |
| 2 | Thur |       | **Quiz.** `r citeTitle("Christian2020Alignment")`. **Ch 3.** |
| 3 | Tues |       | **Quiz.** `r citeTitle("Christian2020Alignment")`. **Ch's 4 & 5.** |
| 3 | Thur |       | **Quiz.** `r citeTitle("Christian2020Alignment")`. **Ch's 6 & 7.** |
| 4 | Tues |       | **Quiz.** `r citeTitle("Christian2020Alignment")`. **Ch's 8 & 9 & Conclusion.** |
| 4 | Thur |       | **Exam.** |
| 5 | Tues |	Crowdsourcing morality | *In-class interactive:* [Decide for whom the car tolls](https://www.moralmachine.net/); and, [Ask Delphi](https://delphi.allenai.org/) |
| 5 | Thur |	 |	**Quiz.** `r citeTitle("AwadEtAl2018MoralMachineExp")`; and, `r citeTitle("BigmanGray2020LifeDeathDecisions")`; and, `r citeTitle("AwadEtAl2020ReplyToLife")`. <br>*Try it yourself:* [Decide for whom the car tolls](https://www.moralmachine.net/). <br>FYI: [Rahwan's TED talk](https://youtu.be/nhCh1pBsS80). <br>(In lecture but not assigned reading: `r citeTitle("Gill2020ConsumerMorality")`; and, `r citeTitle("Novak2020MoralDilemmas")`.) |
| 6 | Tues |	|	**Quiz.** `r citeTitle("JiangEtAl2021DelphiMachineEthics")`; and, `r citeTitle("Vincent2021DelphiComment")`; and, `r citeTitle("JiangEtAl2021DelphiBlog")`. <br>*Try it yourself:* [Ask Delphi](https://delphi.allenai.org/) <br>FYI: [NYT blog](https://www.nytimes.com/2021/11/19/technology/can-a-machine-learn-morality.html). <br>(In lecture but not assigned reading: `r citeTitle("TalatEtAl2021CommentOnDelphi")`.) |
| 6 | Thur | Implementation | **Quiz.** `r citeTitle("MalleScheutz2014MoralRobots")`. |
| 7 | Tues |  | **Quiz.** First parts of `r citeTitle("CervantesEtAl2020ArtificialMoralAgents")`. |
| 7 | Thur | | **Quiz.** Remaining parts of `r citeTitle("CervantesEtAl2020ArtificialMoralAgents")`. <br>(In lecture but not assigned reading: `r citeTitle("TolmeijerEtAl2020MachineEthics")`.) |
| 8 | Tues | | **Quiz.** `r citeTitle("ZoshakDew2021EthicalTheoriesInAMAs")`. <br>FYI: [Video by Zoshak summarizing the article](https://youtu.be/_M14LJYDVqU).  |
| 8 | Thur | | **Quiz.** `r citeTitle("HolyoakPowell2016DeontologicalCoherence")`. (Especially the section on "Deontological coherence as constraint satisfaction".) <!-- ; and, `r citeTitle("Liu2021EmotionRobots")` --> |
| 9 | Tues | |		Review. |
| 9 | Thur | |		**Exam.** |
| Break | | | |
| 10 | Tues | Explainability |	**Quiz.** `r citeTitle("GunningAha2019ExplainableAI")`. |
| 10 | Thur | |		**Quiz.** `r citeTitle("YongLiKanazawa2020Rationalizing")`. <br>(In lecture but not assigned reading: `r citeTitle("Miller2019ExplanationInAI")`. Also preview "moral dumbfounding".) |
| 11 | Tues | Corruptor or Advisor |		**Quiz.** `r citeTitle("KobisEtAl2021BadMachines")`. <br>(In lecture but not assigned reading: `r citeTitle("ZhuEtAl2020MoralRebukes")`.) <br>FYI: [robots in religion](https://www.bbc.com/news/av/technology-58983047). |
| 11 | Thur |	Responsible Use |	**Quiz.** `r citeTitle("Rahwan2018SocialContract")`. <br>(In lecture but not assigned reading: `r citeTitle("Hagendorff2020AIethics")`.) <br>FYI: Cf. the [Belmont principles](https://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/index.html) for human subjects. |
| 12 | Tues |	Attitudes toward robots |	**Quiz.** Chapter 3 "The Machine" of `r citeTitle("WegnerGray2016MindClub")`. <br>(In lecture but not assigned reading: `r citeTitle("GamezEtAl2020ArtificialVirtue")`.) <!-- <br>(Maybe `r citeTitle("Maninger2022ViolationsByArtificial")`)  --> |
| 12 | Thur |	Perspectives |	**Quiz.** `r citeTitle("MartinhoEtAl2021ArtificalMoralAgents")`. |
| 13 | Tues | Human moral psychology |	**Quiz.** `r citeTitle("Pinker2008MoralInstinct")`. <br>And, begin discussion of `r citeTitle("HaidtK2010")`. |
| 13 | Thur | |	**Quiz.** `r citeTitle("HaidtK2010")`, continued. |
| 14 | Tues | Human morality involves relationships |	**Quiz.** `r citeTitle("RaiFiske2011RelationshipRegulation")`. <br>(In lecture but not assigned reading: `r citeTitle("Tomasello2016HumanMorality")`.) <br>See also [Professor Kruschke's course in moral psychology](https://jkkweb.sitehost.iu.edu/jkkteach/P484MoralJudgment/). |
| 14 | Thur | Machine understanding of relationships | **Quiz.** Tentatively: `r citeTitle("TengEtAl2021SocialRelationships")`; and, `r citeTitle("XuEtAl2021SocialRelationRecognition")`. |
| 15 | Tues | Machine ethics *vs* human morality | Prof. Kruschke's perspective: <br>&bullet;  Machine obligations *vs* human obligations (to self, to others in various roles, to various groups, to principles). <br>&bullet; Control of machines *vs* control of humans (through social norms and social sanctions such as reputation, gossip, ostracism). <br>&bullet; Machine explanation *vs* human explanation, justification, recruitment of allies, persuasion. <br>&bullet; Machine motivation *vs* evolved human emotion, cognition, and motivation for social functions. |
| 15 | Thur | | Review and Overview (or possibly study day) |
| Finals | | | **Final Exam**, see registrar info for date and time |


# Learning Objectives

The items below do not exhaust everything to learn from this course, but here are at least a few key points.

  * Be able to identify, define, describe, and explain the central ideas, such as fairness, explainability, and the varieties of implementations of ethics.
    + For each idea (such as fairness, explainability, etc.) explain how human psychology informs, and possibly differs from, the definitions used in machine ethics.
  
  * Be able to apply, analyze, and evaluate those ideas for specific applied cases, such as self-driving cars, decision systems for granting parole, etc.
    + For each application, analyze how the *artificial* moral agent is different from a *human* moral agent in the same situation.


# Grading procedure

## Quizzes

Most classes begin with a short quiz about that day's reading. The purpose of the quiz is to motivate you to prepare for in-class discussion and to recognize your preparation. Each day's quiz consists of a small number of short-answer or multiple choice questions relevant to that day's reading. **The quiz starts promptly at the beginning of class.** Each quiz is worth up to 10 points.

*Your lowest 4 quiz scores will be dropped*. Thus, if you must miss a day because of illness or personal reasons, that day simply counts as a zero and will be one of your 4 dropped scores. There are no make-up quizzes for missed days. The only way that a make-up for a missed quiz could be considered is if you had to miss more than 4 quiz days for reasons beyond your control, in which case notify Prof. Kruschke *as soon as possible*.

## Exams 

There are 3 exams. The purpose of the exams is to help you retrospectively synthesize the readings. Each exam will focus mostly on material from the immediately preceding part of the course, but there will be some questions that comprehensively integrate across all previous material. Each exam is worth 100 points, for 300 points total. *All exams are mandatory*. Make-up exams are given only if you had to miss an exam for reasons beyond your control, in which case you must notify Prof. Kruschke *immediately and in advance if possible*.

## Research proposal 

Graduate students enrolled in P657, but not undergraduates in P457, will compose a research proposal based on the course readings. The proposal should include an introduction that explains how the course readings motivate the proposed research and what novel contribution would be provided by the research. The proposal should explain the methods and procedures of the proposed research, and how they relate to the course readings. The proposal should also explain anticipated results and what type of statistical procedures might be used. The proposal does *not* need to include simulated (or actual) data or statistical analyzes. The proposal should not exceed 5,000 words. The proposal will count as 15% of the final course grade.

## Course grade 

Letter grades in P457 are based on your total points, as a percentile relative to other students in the course. Percentiles are established for P457 separately from P657. There are no pre-set point cutoffs for specific letter grades, nor is there a pre-set quota for how many students can receive A's or B's, etc. Past experience suggests that there will be approximately 30% A's, 40% B's, 25% C's, and 5% D's. For P657, grades will be assigned as is typical for a graduate readings course.

# Information online: Canvas

Our online hub for the course is IU <a href='https://canvas.iu.edu/' target='_blank'>Canvas (https://canvas.iu.edu/)</a>. If you do not have access to Canvas, please notify Prof. Kruschke immediately. *All announcements and discussion will be consolidated into the P457 Canvas site, therefore students who are enrolled in P657 will be given access to the P457 Canvas site*.


# Contact

## Instructor 

<a href='https://jkkweb.sitehost.iu.edu/' target='_blank'>Prof. John Kruschke</a>, kruschke@indiana.edu. Office hours by appointment; please *do* ask. Meetings may be held via Zoom.


<!-- ## Assistant  -->

<!-- Please see info in Canvas. -->


# Disclaimer

All information in this document is subject to change. Changes will be announced in class.

# University Policies

## Academic Integrity 

As a student at IU, you are expected to adhere to the standards detailed in the Code of Student Rights, Responsibilities, and Conduct (Code). Academic misconduct is defined as any activity that tends to undermine the academic integrity of the institution. Violations include: cheating, fabrication, plagiarism, interference, violation of course rules, and facilitating academic dishonesty. When you submit an assignment with your name on it, you are signifying that the work contained therein is yours, unless otherwise cited or referenced. Any ideas or materials taken from another source for either written or oral use must be fully acknowledged. All suspected violations of the Code will be reported to the Dean of Students and handled according to University policies. Sanctions for academic misconduct may include a failing grade on the assignment, reduction in your final course grade, and a failing grade in the course, among other possibilities. If you are unsure about the expectations for completing an assignment or taking a test or exam, be sure to seek clarification from your instructor in advance.

## Note Selling (Don't)

Several commercial services have approached students regarding selling class notes/study guides to their classmates. Selling the instructor's notes/study guides in this course is not permitted. Violations of this policy will be reported to the Dean of Students as academic misconduct (violation of course rules). Sanctions for academic misconduct may include a failing grade on the assignment for which the notes/study guides are being sold, a reduction in your final course grade, or a failing grade in the course, among other possibilities. Additionally, you should know that selling a faculty member's notes/study guides individually or on behalf of one of these services using IU email, or via Canvas may also constitute a violation of IU information technology and IU intellectual property policies; additional consequences may result.


## Online Course Materials

The faculty member teaching this course holds the exclusive right to distribute, modify, post, and reproduce course materials, including all written materials, study guides, lectures, assignments, exercises, and exams. While you are permitted to take notes on the online materials and lectures posted for this course for your personal use, you are not permitted to re-post in another forum, distribute, or reproduce content from this course without the express written permission of the faculty member. Any violation of this course rule will be reported to the appropriate university offices and officials, including to the Dean of Students as academic misconduct.


# References 

